# Generated by Django 4.2.5 on 2023-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.CharField(max_length=3)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('TandC', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Psignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.CharField(max_length=3)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('TandC', models.CharField(max_length=10)),
            ],
        ),
    ]
