# Generated by Django 4.2.5 on 2023-10-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dsignup',
            new_name='Docsignup',
        ),
        migrations.DeleteModel(
            name='Psignup',
        ),
    ]
