# Generated by Django 4.2.5 on 2023-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0002_rename_dsignup_docsignup_delete_psignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.CharField(max_length=3)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('TandC', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Docsignup',
            new_name='Dsignup',
        ),
    ]
