# Generated by Django 4.2.5 on 2023-10-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0003_psignup_rename_docsignup_dsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
