# Generated by Django 4.2.5 on 2023-10-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0004_imagegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
