# Generated by Django 4.2.5 on 2023-10-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0007_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
