# Generated by Django 4.2.5 on 2023-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0010_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='page',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pnumber',
            field=models.IntegerField(),
        ),
    ]
