# Generated by Django 4.2.5 on 2023-10-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0011_alter_appointment_page_alter_appointment_pnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pappiontdate',
            new_name='pappointdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='pappionttime',
            new_name='pappointtime',
        ),
    ]
