# Generated by Django 4.2.5 on 2023-10-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0012_rename_pappiontdate_appointment_pappointdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pstatus',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
