# Generated by Django 4.2.5 on 2023-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0013_appointment_pstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pprescription',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
