# Generated by Django 4.2.5 on 2023-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0014_appointment_pprescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pprescription',
            field=models.FileField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
