# Generated by Django 4.2.5 on 2023-10-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0020_delete_review_appointment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='rate',
            new_name='rating',
        ),
    ]
