# Generated by Django 4.2.5 on 2023-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0022_alter_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
