# Generated by Django 4.2.5 on 2023-10-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0023_alter_appointment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='rating',
            new_name='rate',
        ),
    ]
