# Generated by Django 4.2.5 on 2023-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0024_rename_rating_appointment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rate',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
