# Generated by Django 4.2.5 on 2023-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0032_remove_review_id_alter_review_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
